from sqlalchemy import Column, String, Integer, Float, Boolean, ForeignKey, DateTime, Text, JSON
from sqlalchemy.orm import relationship
from sqlalchemy.sql import func
from sqlalchemy.dialects.postgresql import UUID, TSVECTOR
from pgvector.sqlalchemy import Vector
from app.db.database import Base
import uuid

class User(Base):
    __tablename__ = "users"
    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    email = Column(String, unique=True, index=True, nullable=False)
    password_hash = Column(String, nullable=False)
    created_at = Column(DateTime(timezone=True), server_default=func.now())

    settings = relationship("UserSettings", back_populates="user", uselist=False, cascade="all, delete-orphan")
    feedback_memory = relationship("FeedbackMemory", back_populates="user", uselist=False, cascade="all, delete-orphan")
    papers = relationship("UserPaper", back_populates="user", cascade="all, delete-orphan")

class UserSettings(Base):
    __tablename__ = "user_settings"
    user_id = Column(UUID(as_uuid=True), ForeignKey("users.id", ondelete="CASCADE"), primary_key=True)
    categories = Column(JSON, default=list) # e.g. ["cs.AI"]
    topics = Column(JSON, default=list)
    authors = Column(JSON, default=list)
    filtering_goal = Column(Text, nullable=True)
    distilled_criteria = Column(JSON, default=list) # Auto-generated by GoalDistiller agent
    lexical_query = Column(Text, nullable=True) # Auto-generated by GoalDistiller for BM25 search
    goal_embedding = Column(Vector(768), nullable=True)
    content_interest = Column(JSON, default=list)
    library_explanation_level = Column(String, default="professional")
    notification_email = Column(String, nullable=True)  # Email for top-pick notifications (defaults to login email)
    notification_time = Column(String, nullable=True)
    deep_scan_limit = Column(Integer, default=10)  # How many papers get Marker+Deep Reader (5/10/15)
    pdf_parser_mode = Column(String, default="pypdfium")

    user = relationship("User", back_populates="settings")

class FeedbackMemory(Base):
    __tablename__ = "feedback_memory"
    user_id = Column(UUID(as_uuid=True), ForeignKey("users.id", ondelete="CASCADE"), primary_key=True)
    summarized_feedback = Column(Text, nullable=True)
    rejection_count = Column(Integer, default=0)
    last_updated = Column(DateTime(timezone=True), server_default=func.now(), onupdate=func.now())
    
    user = relationship("User", back_populates="feedback_memory")

class Paper(Base):
    __tablename__ = "papers"
    id = Column(String, primary_key=True) # arxiv_id
    title = Column(String, nullable=False)
    authors = Column(JSON, default=list)
    abstract = Column(Text, nullable=False)
    pdf_url = Column(String, nullable=True)
    source_url = Column(String, nullable=True)
    published_at = Column(DateTime(timezone=True))
    
    # Semantic Search representation mapped to SPECTER2 standard 768 dims
    embedding = Column(Vector(768))
    # Lexical cache bounds mapping for Okapi BM25 text overlap fusion
    search_vector = Column(TSVECTOR)

    user_papers = relationship("UserPaper", back_populates="paper", cascade="all, delete-orphan")

class UserPaper(Base):
    __tablename__ = "user_papers"
    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    user_id = Column(UUID(as_uuid=True), ForeignKey("users.id", ondelete="CASCADE"), index=True)
    paper_id = Column(String, ForeignKey("papers.id", ondelete="CASCADE"), index=True)
    status = Column(String, default="feed", index=True) # Domain: [feed, accepted, rejected]
    agent_score = Column(Float, nullable=True)
    agent_explanation = Column(Text, nullable=True)
    user_comment = Column(Text, nullable=True)
    extracted_markdown = Column(Text, nullable=True)  # Cached Marker PDF output
    is_top_pick = Column(Boolean, default=False)  # Top 3 flag for notifications
    created_at = Column(DateTime(timezone=True), server_default=func.now())

    user = relationship("User", back_populates="papers")
    paper = relationship("Paper", back_populates="user_papers")

class PaperExplanation(Base):
    __tablename__ = "paper_explanations"
    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    user_paper_id = Column(UUID(as_uuid=True), ForeignKey("user_papers.id", ondelete="CASCADE"), index=True)
    level = Column(String, nullable=False) # Domain: [professional, student, kid]
    explanation = Column(Text, nullable=False)
    created_at = Column(DateTime(timezone=True), server_default=func.now())
