"""create tables

Revision ID: b43cd89b88f1
Revises: 0001
Create Date: 2026-04-03 10:05:46.815900

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import pgvector

# revision identifiers, used by Alembic.
revision: str = 'b43cd89b88f1'
down_revision: Union[str, None] = '0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('papers',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('authors', sa.JSON(), nullable=True),
    sa.Column('abstract', sa.Text(), nullable=False),
    sa.Column('pdf_url', sa.String(), nullable=True),
    sa.Column('source_url', sa.String(), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=768), nullable=True),
    sa.Column('search_vector', postgresql.TSVECTOR(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('feedback_memory',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('summarized_feedback', sa.Text(), nullable=True),
    sa.Column('rejection_count', sa.Integer(), nullable=True),
    sa.Column('last_updated', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('user_papers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('paper_id', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('agent_score', sa.Float(), nullable=True),
    sa.Column('agent_explanation', sa.Text(), nullable=True),
    sa.Column('user_comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['paper_id'], ['papers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_papers_paper_id'), 'user_papers', ['paper_id'], unique=False)
    op.create_index(op.f('ix_user_papers_status'), 'user_papers', ['status'], unique=False)
    op.create_index(op.f('ix_user_papers_user_id'), 'user_papers', ['user_id'], unique=False)
    op.create_table('user_settings',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('categories', sa.JSON(), nullable=True),
    sa.Column('topics', sa.JSON(), nullable=True),
    sa.Column('authors', sa.JSON(), nullable=True),
    sa.Column('filtering_goal', sa.Text(), nullable=True),
    sa.Column('distilled_criteria', sa.JSON(), nullable=True),
    sa.Column('content_interest', sa.JSON(), nullable=True),
    sa.Column('library_explanation_level', sa.String(), nullable=True),
    sa.Column('notification_time', sa.String(), nullable=True),
    sa.Column('pdf_parser_mode', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('paper_explanations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_paper_id', sa.UUID(), nullable=True),
    sa.Column('level', sa.String(), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_paper_id'], ['user_papers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_paper_explanations_user_paper_id'), 'paper_explanations', ['user_paper_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_paper_explanations_user_paper_id'), table_name='paper_explanations')
    op.drop_table('paper_explanations')
    op.drop_table('user_settings')
    op.drop_index(op.f('ix_user_papers_user_id'), table_name='user_papers')
    op.drop_index(op.f('ix_user_papers_status'), table_name='user_papers')
    op.drop_index(op.f('ix_user_papers_paper_id'), table_name='user_papers')
    op.drop_table('user_papers')
    op.drop_table('feedback_memory')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('papers')
    # ### end Alembic commands ###
